config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'

  resources :articles
  resources :article_images
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
 	
 	extend FriendlyId
  paginates_per 30
  has_attached_file :image_description, styles: { medium: "300x300>", thumb: "100x100>", banner: "900x300" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_description, content_type: /\Aimage\/.*\z/

  friendly_id :heading, :use =>  [:slugged, :finders]
  has_many :sections

  accepts_nested_attributes_for :sections, :reject_if => lambda { |param| param[:content].blank? }, :allow_destroy => true

end

app/models/article_image.rb
class ArticleImage < ApplicationRecord
  has_attached_file :visual, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :visual, content_type: /\Aimage\/.*\z/
end

app/models/section.rb
class Section < ApplicationRecord

	belongs_to :article
	has_many :section_images
  has_attached_file :image_description, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_description, content_type: /\Aimage\/.*\z/
	accepts_nested_attributes_for :section_images

end

app/models/section_image.rb
class SectionImage < ApplicationRecord
	belongs_to :section
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/article_images_controller.rb
class ArticleImagesController < ApplicationController

	skip_before_action :verify_authenticity_token

	def create
		file = params[:file]
		article_image = ArticleImage.create(visual: file)
		render json: { location: article_image.visual.url }
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def show 
		
	end

	def index
		respond_to do |format|
			@articles = Article.page(params[:page])
			format.js
		end
	end

	def show
		@article = Article.friendly.find(params[:id])
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
		@articles = Article.page
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_images_helper.rb
module ArticleImagesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/articles/_articles.html.erb
<% @articles.each do |article| %>
  <div class="card mb-4">
    <div class="card-body">
      <h2 class="card-title">
        <%= article.heading %>
      </h2>
      <p class="card-text">
        <%= article.short_description%>
      </p>
      <%= link_to article_path(article), class: "btn btn-primary" do  %> 
        Read More
        &rarr;
      <% end %>
    </div>
  </div>
  <br>
<% end %>

app/views/articles/index.js.erb
$('#duk-articles').append("<%= escape_javascript render(:partial => 'articles/articles') %>");
<% if @articles.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript paginate(@articles, params: {controller: 'articles', action: 'index'}) %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/articles/show.html.erb
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<% content_for :meta_og do %>
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="douknow.in" />
  <meta property="og:title" content="<%= @article.heading%>" />
  <meta property="og:description" content="" />
  <meta name="description" content="">
  <meta property="og:image" content="<%= asset_url(@article.image_description.url)%>" />
<% end %>

<h3 class="tittle"><%= @article.heading%></h3>
<div class="single">
  <div class="b-bottom">
  <%= @article.content.html_safe%>
  </div>
</div>

<div class="addthis_inline_share_toolbox"></div>
<!-- <div class="single-bottom">
  <div class="single-middle">
     <ul class="social-share">
        <li><span>SHARE</span></li>
        <li><a href="#"><i> </i></a></li>
        <li><a href="#"><i class="tin"> </i></a></li>
        <li><a href="#"><i class="message"> </i></a></li>
     </ul>
     <a href="#"><i class="arrow"> </i></a>
     <div class="clearfix"> </div>
  </div>
</div> -->
<div class="clearfix"></div>

app/views/homes/index.html.erb
<div class="banner">
</div>
<!--//banner-->
<!--/top-news-->
<div class="top-news">
 <div class="top-inner second">
   <%= render partial: "articles/articles"%>
   <div id="infinite-scrolling" class="hidden">
     <%= paginate @articles, params: {controller: 'articles', action: 'index'} %>
   </div>
   <div class="clearfix"> </div>
 </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
  </div>
  <!-- /.container -->
</footer>

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-113797198-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-113797198-1');
</script>

app/views/layouts/_nav_bar.html.erb
      <div class="h-top" id="home">
         <div class="top-header">
            <ul class="cl-effect-16 top-nag">
               <li><a href="/" data-hover="Do-U-Know">Do-U-Know</a></li>
<!--                <li><a href="about.html" data-hover="About">About</a></li>
               <li><a href="services.html" data-hover="SERVICES">SERVICES</a></li>
               <li><a href="login.html" data-hover="Login">Login</a></li>
               <li><a href="contact.html" data-hover="CONTACT">Contact</a></li> -->
            </ul>
            <div class="clearfix"></div>
         </div>
      </div>

app/views/layouts/_one_signal_notification.html.erb
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
  var OneSignal = window.OneSignal || [];
  OneSignal.push(function() {
    OneSignal.init({
      appId: "37fe424f-2ec3-40fc-9f90-c2cc622a3ad3",
    });
  });
</script>

app/views/layouts/_right_section.html.erb
<div class="banner-right-text">
   <h3 class="tittle">Most Popular</h3>
   <!--/general-news-->
   <div class="general-news">
      <div class="general-inner">
         <div class="general-text">
            <a href="single.html">
              <%= image_tag "/assets/gen1.jpg", class: "img-responsive", alt: "" %>
            </a>
            <p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
         </div>
         <div class="edit-pics">
            <div class="editor-pics">
              <div class="col-md-3 item-pic">
              	<%= image_tag "/assets/f4.jpg", class: "  img-responsive", alt: "" %>
              </div>
               <div class="col-md-9 item-details">
                  <h5 class="inner two"><a href="single.html">New iPad App to simulate your Guitar</a></h5>
               </div>
               <div class="clearfix"></div>
            </div>
            <div class="editor-pics">
               <div class="col-md-3 item-pic">
                  <%= image_tag "/assets/f1.jpg", class: "img-responsive", alt: "" %>
               </div>
               <div class="col-md-9 item-details">
                  <h5 class="inner two"><a href="single.html">New iPad App to simulate your Guitar</a></h5>
               </div>
               <div class="clearfix"></div>
            </div>
            <div class="editor-pics">
               <div class="col-md-3 item-pic">
									<%= image_tag "/assets/f1.jpg", class: "img-responsive", alt: "" %>
               </div>
               <div class="col-md-9 item-details">
                  <h5 class="inner two"><a href="single.html">New iPad App to simulate your Guitar</a></h5>
               </div>
               <div class="clearfix"></div>
            </div>
            <div class="editor-pics">
               <div class="col-md-3 item-pic">
                  <%= image_tag "/assets/f4.jpg", class: "img-responsive", alt: "" %>
               </div>
               <div class="col-md-9 item-details">
                  <h5 class="inner two"><a href="single.html">New iPad App to simulate your Guitar</a></h5>
               </div>
               <div class="clearfix"></div>
            </div>
         </div>
         <div class="media">
            <h3 class="tittle media">Media <i class="glyphicon glyphicon-floppy-disk"></i></h3>
            <div class="general-text two">
               <a href="single.html">
               	<%= image_tag "/assets/gen3.jpg", class: "img-responsive", alt: "" %>
               </a>
               <h5 class="top"><a href="single.html">Consetetur sadipscing elit</a></h5>
            </div>
         </div>
         <div class="general-text two">
            <a href="single.html">
            	<%= image_tag "/assets/gen2.jpg", class: "img-responsive", alt: "" %>
            </a>
            <h5 class="top"><a href="single.html">Consetetur sadipscing elit</a></h5>
         </div>
      </div>
   </div>
   <!--//general-news-->
   <!--/news-->
   <!--/news-->
</div>

app/views/layouts/_share_this.html.erb
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5a7c278784459716"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Do-U-Know</title>
		<%= csrf_meta_tags %>
		<%= render partial: "layouts/google_analytics" %>
		<%= render partial: "layouts/share_this"%>
		<%#= render partial: "layouts/one_signal_notification"%>
		<%= stylesheet_link_tag 'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<link href='//fonts.googleapis.com/css?family=Open+Sans:700,700italic,800,300,300italic,400italic,400,600,600italic' rel='stylesheet' type='text/css'>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="author" content="">
		<meta name="keywords" content="do you know, unknown facts, did you know, facts, science fact, health fact, Sex fact, mythology fact, historical facts" />
		<%= yield :meta_og %>
    <script type="text/javascript">
       jQuery(document).ready(function($) {
       	$(".scroll").click(function(event){		
       		event.preventDefault();
       		$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
       	});
       });
    </script>
	</head>

  <body>
  	<%= render partial: "layouts/nav_bar" %>
		<div class="full">
		  <div class="col-md-9 main">
	      <div class="banner-section">
	    		<%= yield %>
	    	</div>
		    <%= render partial: "layouts/right_section" %>
		    <div class="clearfix"> </div>
		  </div>
		  <div class="clearfix"> </div>
		</div>
		<script type="text/javascript">
		   $(document).ready(function() {
		    /*
		    var defaults = {
		          containerID: 'toTop', // fading element id
		      containerHoverID: 'toTopHover', // fading element hover id
		      scrollSpeed: 1200,
		      easingType: 'linear' 
		      };
		    */
		    
		    $().UItoTop({ easingType: 'easeOutQuart' });
		    
		   });
		</script>
		<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	</body>    	
</html>